name: run-tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
        php: [8.4, 8.3, 8.2, 8.1]
        laravel: ['10.*', '11.*', '12.*']
        stability: [prefer-stable]
        include:
          - laravel: 10.*
            testbench: ^9.0
          - laravel: 10.*
            testbench: ^8.0
          - laravel: 9.*
            testbench: ^7.0
          - laravel: 11.*
            testbench: ^10.0
          - laravel: 12.*
            testbench: ^11.0
        exclude:
          - laravel: 12.*
            php: 8.1

    name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.stability }} - ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo
          coverage: none

      - name: Install dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update --no-scripts
          composer update --${{ matrix.stability }} --prefer-dist --no-interaction

      - name: Execute tests
        run: |
          npm install
          vendor/bin/pest
